--CREATING NEW SECUENCE
CREATE SEQUENCE product_code
  START WITH 1000
  INCREMENT BY 1;


--CALL SECUENCE IN SQL EDITOR
SELECT nextval('product_code');

--CREATE FUNCTION TO CALL SECUENCE SINCE SUPABASE REPOSITORY
CREATE OR REPLACE FUNCTION get_next_product_code()
RETURNS bigint
LANGUAGE sql
AS $$
  SELECT nextval('product_code');
$$;


--CALL FUNCTION IN SQL EDITOR
SELECT get_next_product_code()

--EXAMPLE TO CREATE A FOREIG KEY IN SOME TABLE
ALTER TABLE products
ADD CONSTRAINT fk_products_category
FOREIGN KEY (category_id)
REFERENCES category (id)
ON UPDATE CASCADE
ON DELETE SET NULL;